---
tasks:
  prefiltered_feed:
    verify_ssl_certificates: no
    set:
      path: /transmission/TV_Shows/
    download: yes
    inputs:
      - rss:
          # ----------------------------------------- #
          # https://webtorrent.io/free-torrents
          # https://flexget.com/Plugins/rss
          # ----------------------------------------- #
          ## RSS feed just "Big Buck Bunny"
          url: https://politepol.com/fd/18cDQ0iwMHzF
          # ----------------------------------------- #
          ## RSS feed all of it 
          #url: https://politepol.com/fd/Wc5g5dtmSyBQ
          title: link
    accept_all: yes
    transmission:
      host: localhost
      port: 9091
      username: TUSERNAME
      password: TPASSWORD
    only_new: yes
  #tv_shows:
  #  quality: 720p|1080p
  #  set:
  #    path: /transmission/TV_Shows/{{ series_name|replace(' ','_') }}/Season_{{series_season}}
  #  inputs:
  #    - rss:  https://showrss.info/show/ZzXxYy.rss
  #  exists_series:
  #    - "/transmission/TV_Shows"
  #  # fetch all the feed series
  #  all_series: yes
  #  limit_new: 10
  #  transmission:
  #    host: localhost
  #    port: 9091
  #    username: TUSERNAME
  #    password: TPASSWORD
  #  only_new: yes
  clean:
    priority: 3
    clean_transmission:
      host: localhost
      port: 9091
      username: TUSERNAME
      password: TPASSWORD
      finished_for: 1 minutes
      delete_files: No
    disable: details
